### ISSUE TITLE
Timeout when fetching remote list

### ISSUE THREAD

**Issue by kaioduarte** [Schniz/fnm#371]
I'm getting the timeout error frequently and it works both via `wget` or `nvm`, am I missing anything? I'm on the latest version (1.22.8) and using WSL2.

![image](https://user-images.githubusercontent.com/11046907/105181502-cad6f480-5b23-11eb-80c8-67a784dee1e2.png)

**Comment by Schniz** [comment]
Hi, I can't reproduce this. Maybe you're on a flakey network?

**Comment by kaioduarte** [comment]
@Schniz not really. I just tried again and it's still not working, it works instantly with Python also
![image](https://user-images.githubusercontent.com/11046907/105480162-4f994e00-5c9d-11eb-861a-8bdbe1219c07.png)

**Comment by Schniz** [comment]
Interesting.
I wonder what the following will tell us, maybe `reqwests` will say it has some troubles or anything we can use to debug that:

```
RUST_LOG=reqwest=debug fnm ls-remote > /dev/null
```

**Comment by Schniz** [comment]
(the `> /dev/null` is not necessary, I just do that because it works on my machine and the output is very long)

**Comment by kaioduarte** [comment]
nothing helpful @Schniz 

![image](https://user-images.githubusercontent.com/11046907/105486448-65f7d780-5ca6-11eb-9682-a12354073b80.png)

**Comment by Schniz** [comment]
Hi, been trying to replicate but I just can't seem to reproduce it locally. So I'm not sure I'll be able to help.

Can you build it locally and see if it still fails?

**Comment by kaioduarte** [comment]
@Schniz it worked after building it locally.

![image](https://user-images.githubusercontent.com/11046907/106396291-ea60fd80-63fe-11eb-9025-81eae1ec3a58.png)

**Comment by Schniz** [comment]
well, I have no idea why it happens. Haven't used Windows in a long time, and it didn't happen to me when I made fnm compile and pass tests on a Windows VM 🤔

Feel free to try making it fail on CI machines so we'll be able to fix it for more people 😃 

Sorry that I can't help more than that.

**Comment by kaioduarte** [comment]
hey @Schniz, I manage to make it work on CI with another GitHub Action, and using a different target (`x86_64-unknown-linux-gnu`).

```yaml
jobs:
  build_static_linux_binary:
    name: "Build static Linux binary"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build-musl
      uses: gmiam/rust-musl-action@master
      with:
        args: cargo build --target x86_64-unknown-linux-gnu --release
    - uses: actions/upload-artifact@v2
      with:
        name: fnm-linux-gnu
        path: target/x86_64-unknown-linux-gnu/release/fnm
```

Accordingly [to Rust docs](https://doc.rust-lang.org/nightly/rustc/platform-support.html#tier-2) the target used in this project it's not guaranteed to produce a working build.

Can you test the artifact generated on your computer?
https://github.com/kaioduarte/fnm/actions/runs/549437391
